# Generated by Django 5.0.1 on 2024-06-09 11:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTable',
            fields=[
                ('companyId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=100)),
                ('companyLocation', models.CharField(max_length=500)),
                ('about', models.TextField()),
                ('type', models.CharField(choices=[('It', 'IT'), ('Non-IT', 'Non-IT'), ('mobile', 'Mobile')], max_length=100)),
            ],
        ),
    ]
